name: Aeternum
version: 1.0
main: wcorrupt.aeternum.Aeternum
api-version: 1.20
author: YourName
description: A plugin for managing special box areas and various other commands.

commands:
  fly:
    description: Toggle fly mode.
    usage: /fly [player]
    permission: aeternum.fly

  flyspeed:
    description: Set fly speed.
    usage: /flyspeed <1-10>
    permission: aeternum.flyspeed

  freeze:
    description: Freeze a player.
    usage: /freeze <player>
    permission: aeternum.freeze

  unfreeze:
    description: Unfreeze a player.
    usage: /unfreeze <player>
    permission: aeternum.unfreeze
  giveinfcart:
    permission: op
  createwarp:
    description: Create a warp point
    usage: /createwarp <name>
    permission: op
  warp:
    description: Warp to a point
    usage: /warp <name>
  deletewarp:
    description: Delete a warp point
    usage: /deletewarp <name>
    permission: op

  createkit:
    description: Create a kit from your current inventory.
    usage: /createkit <name>
    permission: op
  kit:
    description: Equip a kit.
    usage: /kit <name>
    permission: aeternum.kit
  deletekit:
    description: Delete a kit.
    usage: /deletekit <name>
    permission: op
  spawn:
    description: Teleports the player to spawn after 5 seconds if they don't move.
    usage: /spawn
  spawnadmin:
    description: Instantly teleports the player to spawn if they have the permission.
    usage: /spawnadmin
    permission: aeternum.spawnadmin
    permission-message: You do not have permission to use this command.
  giveshieldbreaker:
    description: "Gives the item in hand a custom tag"
    permission: op
  trash:
    description: "Opens a trash GUI to dispose of items"
    permission: "aeternum.trash"
    usage: "/trash"
  setafkitem:
    description: "Set the item to be given to players in the AFK room."
    usage: "/setafkitem <item>"
    permission: op
  itemname:
    permission: aeternum.itemname

  portalwand:
    description: Gives a portal wand with a specified command.
    usage: /portalwand <command>
    permission: op
    permission-message: You do not have permission to use this command.

  staffchat:
    description: Toggle staff chat or send a message in staff chat.
    usage: /staffchat [message]
    permission: staff.chat
permissions:
  aeternum.fly:
    description: Allows toggling fly mode.
    default: op
  aeternum.flyspeed:
    description: Allows setting fly speed.
    default: op
  aeternum.freeze:
    description: Allows the player to use the /freeze command.
    default: op
  aeternum.unfreeze:
    description: Allows the player to use the /unfreeze command.
    default: op
  aeternum.itemname:
    description: Allows renaming items with custom names.
    default: op
  aeternum.kit:
    default: op
  aeternum.spawnadmin:
    default: op
  aeternum.trash:
    default: op
  aeternum.whitechat:
    default: op
  staff.chat:
    description: Allows access to staff chat commands and messages.
    default: op